SELECT CTRNO,NAMEdriver FROM SIGNOFFdriver WHERE SIDING='null' AND SIDING2='null' AND SIDING3='null' AND SIDING4='null' AND SIDING5='null'
AND SIDING6='null' AND SIDING7='null' AND SIDING8='null' AND SIDING9='null' AND  SIDING10='null' AND SIDING11='null' AND SIDING12='null'
AND SHUNTING>0 AND DATE2>'15-JUN-04' order by namedriver
/
